var restaurant,map,db,reviews,idbreviews;function getQueryVariable(a){for(var b=window.location.search.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return d[1]}return!1}
window.addEventListener("online",function(){var a=parseInt(getQueryVariable("id"));console.log("Back online! ID is "+a);db=new Dexie("reviews1-db");db.version(1).stores({ny:"id,restaurant_id,[id+restaurant_id]"});db.ny.where("[id+restaurant_id]").between([1E3,a],[2E3,a]).toArray().then(function(a){return a}).then(function(b){"undefined"==typeof b||null==b||0==b.length?console.log("No offline reviews added."):(b.forEach(function(a){var b=a.restaurant_id,c=a.name,f=a.rating,g=a.comments;addReview(b,
c,f,g).then(function(a){db.table("ny").put({id:a.id,restaurant_id:b,name:c,createdAt:a.createdAt,updatedAt:a.updatedAt,rating:f,comments:g})})}),db=new Dexie("reviews1-db"),db.version(1).stores({ny:"id,restaurant_id,[id+restaurant_id]"}),db.ny.where("[id+restaurant_id]").between([1E3,a],[2E3,a])["delete"]().then(function(a){console.log("Deleted "+a+" objects")}))})});
window.initMap=function(){fetchRestaurantFromURL(function(a,b){a?console.error(a):(self.map=new google.maps.Map(document.getElementById("map"),{zoom:16,center:b[0].latlng,scrollwheel:!1}),fillBreadcrumb(),DBHelper.mapMarkerForRestaurant(self.restaurant,self.map))})};
fetchRestaurantFromURL=function(a){if(self.restaurant)a(null,self.restaurant);else{var b=getParameterByName("id");b?(document.getElementById("id").value=b,DBHelper.fetchRestaurantById(b,function(b,d){(self.restaurant=d)?(fillRestaurantHTML(),a(null,d)):console.error(b)})):(error="No restaurant id in URL",a(error,null))}};
fillRestaurantHTML=function(a){a=void 0===a?self.restaurant:a;document.getElementById("restaurant-name").innerHTML=a[0].name;document.getElementById("restaurant-address").innerHTML=a[0].address;var b=document.getElementById("restaurant-img");b.className="restaurant-img";b.src=DBHelper.imageUrlForRestaurant(a[0]);b.alt="Image of restaurant "+a[0].name;document.getElementById("restaurant-cuisine").innerHTML=a[0].cuisine_type;a[0].operating_hours&&fillRestaurantHoursHTML();navigator.onLine?DBHelper.fetchReviewsByRestaurantId(a[0].id,
function(b,d){(self.reviews=d)?(db=new Dexie("reviews1-db"),db.version(1).stores({ny:"id,restaurant_id,[id+restaurant_id]"}),db.ny.bulkPut(self.reviews).then(function(a){console.log("Copying data to indexed db");console.log("Last data id was: "+a)})["catch"](Dexie.BulkError,function(a){console.error("Copying did not fully succeed.")}),db.ny.where("[id+restaurant_id]").between([1E3,a[0].id],[2E3,a[0].id]).toArray().then(function(a){return a}).then(function(b){"undefined"==typeof b||null==b||0==b.length?
console.log("No offline reviews added."):(b.forEach(function(a){var b=a.restaurant_id,c=a.name,d=a.rating,e=a.comments;addReview(b,c,d,e).then(function(a){db.table("ny").put({id:a.id,restaurant_id:b,name:c,createdAt:a.createdAt,updatedAt:a.updatedAt,rating:d,comments:e})})}),db=new Dexie("reviews1-db"),db.version(1).stores({ny:"id,restaurant_id,[id+restaurant_id]"}),db.ny.where("[id+restaurant_id]").between([1E3,a[0].id],[2E3,a[0].id])["delete"]().then(function(a){console.log("Deleted "+a+" objects")}))}),
DBHelper.fetchReviews(a[0].id,function(a,b){if(self.idbreviews=b)fillIDBReviewsHTML(),callback(null,b)})):b?DBHelper.fetchReviews(a[0].id,function(a,b){if(self.reviews=b)fillReviewsHTML(),callback(null,b)}):console.log("no reviews")}):DBHelper.fetchReviews(a[0].id,function(a,b){if(self.reviews=b)fillReviewsHTML(),callback(null,b)})};
fillRestaurantHoursHTML=function(a){a=void 0===a?self.restaurant[0].operating_hours:a;var b=document.getElementById("restaurant-hours"),c;for(c in a){var d=document.createElement("tr"),e=document.createElement("td");e.innerHTML=c;d.appendChild(e);e=document.createElement("td");e.innerHTML=a[c];d.appendChild(e);b.appendChild(d)}};
fillReviewsHTML=function(a){a=void 0===a?self.reviews:a;var b=document.getElementById("reviews-container");if(a){var c=document.getElementById("reviews-list");a.forEach(function(a){c.appendChild(createReviewHTML(a))});b.appendChild(c)}else a=document.createElement("p"),a.innerHTML="No reviews yet!",b.appendChild(a)};
fillIDBReviewsHTML=function(a){a=void 0===a?self.idbreviews:a;var b=document.getElementById("reviews-container");if(a){var c=document.getElementById("reviews-list");c.innerHTML="";a.forEach(function(a){c.appendChild(createReviewHTML(a))});b.appendChild(c)}else a=document.createElement("p"),a.innerHTML="No reviews yet!",b.appendChild(a)};
createReviewHTML=function(a){var b=document.createElement("li");b.tabIndex=0;var c=document.createElement("p");c.innerHTML=a.name;b.appendChild(c);c=document.createElement("p");c.innerHTML=(new Date(a.updatedAt)).toLocaleString();b.appendChild(c);c=document.createElement("p");c.innerHTML="Rating: "+a.rating;b.appendChild(c);c=document.createElement("p");c.innerHTML=a.comments;b.appendChild(c);return b};
fillBreadcrumb=function(a){a=void 0===a?self.restaurant:a;var b=document.getElementById("breadcrumb"),c=document.createElement("li");c.innerHTML=a[0].name;b.appendChild(c)};getParameterByName=function(a,b){b||(b=window.location.href);a=a.replace(/[\[\]]/g,"\\$&");var c=(new RegExp("[?&]"+a+"(=([^&#]*)|&|#|$)")).exec(b);return c?c[2]?decodeURIComponent(c[2].replace(/\+/g," ")):"":null};
function addReview(a,b,c,d){a={name:b,rating:parseInt(c),comments:d,restaurant_id:parseInt(a)};console.log("Sending review: ",a);a={method:"POST",body:JSON.stringify(a),headers:new Headers({"Content-Type":"application/json"})};return fetch("http://localhost:1337/reviews",a).then(function(a){var b=a.headers.get("content-type");return b&&-1!==b.indexOf("application/json")?a.json():"API call successfull"}).then(function(a){return a})["catch"](function(a){console.log("error:",a)})}
function generateRandomInteger(a,b){return Math.floor(a+Math.random()*(b+1-a))}var formValid;
function validateForm(a){formValid=1;var b=parseInt(document.forms.myForm.id.value),c=document.forms.myForm.name.value,d=parseInt(document.forms.myForm.rating.value),e=document.forms.myForm.comments.value;resetErrors();document.getElementById("reviewAddedMessage").innerHTML="";0==document.forms.myForm.rating.value&&applyError("rating","&nbsp;You must choose a rating.");""==document.forms.myForm.name.value&&(document.getElementById("nameErrorHidden").innerHTML="You must enter your name.",applyError("name",
"&nbsp;You must enter your name."));if(0==formValid)return a.preventDefault(),!1;a.preventDefault();var f=Date.now();if(navigator.onLine)addReview(b,c,d,e).then(function(a){db=new Dexie("reviews1-db");db.version(1).stores({ny:"id,restaurant_id,[id+restaurant_id]"});db.table("ny").put({id:a.id,restaurant_id:b,name:c,createdAt:a.createdAt,updatedAt:a.updatedAt,rating:d,comments:e});DBHelper.fetchReviews(b,function(a,b){if(self.idbreviews=b)fillIDBReviewsHTML(),callback(null,b)})}),document.getElementById("reviewAddedMessage").innerHTML=
"Review Added!",document.forms.myForm.reset();else return a.preventDefault(),db=new Dexie("reviews1-db"),db.version(1).stores({ny:"id,restaurant_id,[id+restaurant_id]"}),a=generateRandomInteger(1E3,1999),db.table("ny").put({id:a,restaurant_id:b,name:c,createdAt:f,updatedAt:f,rating:d,comments:e}),DBHelper.fetchReviews(b,function(a,b){if(self.idbreviews=b)fillIDBReviewsHTML(),callback(null,b)}),document.getElementById("reviewAddedMessage").innerHTML="Review Added!",document.forms.myForm.reset(),!1}
function applyError(a,b){document.getElementById(a+"Error").innerHTML=b;document.getElementById(a).focus();formValid=0}function resetErrors(){document.getElementById("nameError").innerHTML="";document.getElementById("nameErrorHidden").innerHTML="";document.getElementById("ratingError").innerHTML=""};